### ISSUE TITLE
DNX Core 5

### ISSUE THREAD

**Issue by rpaschoal** [tmsmith/Dapper-Extensions#113]
Hello Everyone,

Do you guys plan to release a version compatible with DNX Core 5?

Cheers!

**Comment by ryancosans** [comment]
+1

**Comment by rpaschoal** [comment]
@ryancosans,

If you are in a hurry with a project, have a look at this pull request that I did:

https://github.com/tmsmith/Dapper-Extensions/pull/115

It is not official but I am using it with a DNX Core 5 project and it is working fine so far =)

Cheers!

**Comment by ryancosans** [comment]
@rpaschoal Yeah I noticed that I will pull it and give this it a go first thing tomorrow. I will let you know how I get on :+1:

**Comment by rpaschoal** [comment]
@ryancosans 

Good! I hope it can be useful to you!

See ya!

**Comment by ryanelian** [comment]
Hey guys, slightly off-topic but still relevant due to future .NET applications can be build against .NET Core.

Is Dapper-Extensions still being actively maintained? Are there forks of this that are being actively maintained? Should I be worried that there are many pending pull requests and development apparently ceased 2 years ago?

Has anyone tried https://github.com/ryanwatson/Dapper.Extensions.Linq instead? Where do people discuss about Dapper.Extensions.Linq issues?

**Comment by tmsmith** [comment]
latest master

**Comment by motoyugota** [comment]
I tried pulling down the 1.5.0 nuget package from here and it still comes back as not compatible with Microsoft.NETCore.App - says it's only compatible with .net 4.5 and 4.6
