### ISSUE TITLE
InsetAsync Often Fails but no error message

### ISSUE THREAD

**Issue by davidbuckleyni** [tmsmith/Dapper-Extensions#221]
Sometimes Insert Async would fail but it doesn't produce an error message for me is they're a way to find out what has go wrong in the model.

**Comment by AartBluestoke** [comment]
@davidbuckleyni is this a case where no Exception is thrown where one is expected, or is this a case where the error message doesn't help you know what the cause was?

If it is the latter then there may be little that dapper can do as some databases (eg: sql sever versions before 2019) are a bit vague about why the write didn't happen.

Do you have an example of what specifically did/didn't occur, and what you expected/ would like to see instead?

**Comment by davidbuckleyni** [comment]
it ended up being null dates was the issue

**Comment by davidbuckleyni** [comment]
Your libarays are amazing only wish c# for loops was faster for placing
item into a list I have to convert it from one list to another.
