### ISSUE TITLE
Future plans for this project

### ISSUE THREAD

**Issue by goforgold** [tmsmith/Dapper-Extensions#234]
Are there any plans to revive this project?

There is a pile of Pull Requests and the last commit was done about 4 years back.

**Comment by mewajda** [comment]
I would be willing and love to take over ownership of this project to keep it going and bring it up-to-date

**Comment by AartBluestoke** [comment]
It's Apache licensed - there's nothing stopping someone from forking the repo, letting people here know and starting a new dapper-Extensions-netCore5 (or something) nuget package

**Comment by valfrid-ly** [comment]
I forked and I'm evolving it, but it would be really great to keep one only and not many different ones. I got it on netstandard, netcore and it's possible with only one project to have it compatible with net5 too.

**Comment by valfrid-ly** [comment]
There are lots of Pull Requests to be approved and it will bring lots of new features and bug fixes

**Comment by AartBluestoke** [comment]
agreed, but in the absence of a true maintainer, that's the best the community can do. you can probably cherry-pick the pr's over to your branch, but i'm not sure how much effort that would be.

**Comment by tmsmith** [comment]
Been a little sidetracked with life. I would like to get this project relaunched. As such I have been looking at splitting the sql generation into another package to clean this up. Probably start with getting it up and running in core. I had a couple of people volunteer to help care this forward, but that seems to have fallen thru.

So if someone wants to jump in and help that would be grand.

**Comment by JMan7777** [comment]
Would be great to see this project or a fork again been maintained (especially for .NET core 3.1, 5, 6).

Currently I'm using the fork below since it has already some important bug fixes:

[https://github.com/K1vs/Dapper-Extensions](https://github.com/K1vs/Dapper-Extensionsl)

, but it's also not maintained anymore. Maybe some of the bug fixes can be migrated.

Additionally I could provide BulkInsert and BulkDelete code for MS SQL as that was something I needed for myself and there was nothing around.  It's helping a lot with performance when you need to add/delete thousands/millions of records.

**Comment by valfrid-ly** [comment]
@tsmith, you can count with me. 

I'm already making some changes to it in my fork https://github.com/valfrid-ly/Dapper-Extensions and made a PR to this project.

If you let me, I can start approving or rejecting PRs and we can get it running again.

I know people who uses it and would like to do not have it up to date.

I also alread migrated the project for the new VS2017 standard where we can have multiple target frameworks inside only one .csproj.
