### ISSUE TITLE
Casting error in Get and GetAsync methods 

### ISSUE THREAD

**Issue by hfrances** [tmsmith/Dapper-Extensions#262]
Hello, when I try to call to Get / GetAsync methods, I get an error.

**Code examples:**
```cs
Entities.MyItem rdo;

rdo = conn.Get<Entities.MyItem>(new { Id = pk });
rdo = await conn.GetAsync<Entities.MyItem>(new { Id = pk });
```

**Error message:**
_Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot implicitly convert type 'object' to 'System.Collections.Generic.IEnumerable<Entities.MyItem>'. An explicit conversion exists (are you missing a cast?)
  Stack Trace:
      at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at DapperExtensions.DapperImplementor.InternalGet[T](IDbConnection connection, Object id, IDbTransaction transaction, Nullable`1 commandTimeout, IList`1 colsToSelect, IList`1 includedProperties)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute7[T0,T1,T2,T3,T4,T5,T6,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6)
   at DapperExtensions.DapperImplementor.Get[T](IDbConnection connection, Object id, IDbTransaction transaction, Nullable`1 commandTimeout, IList`1 includedProperties)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute5[T0,T1,T2,T3,T4,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4)
   at DapperExtensions.DapperExtensions.Get[T](IDbConnection connection, Object id, IDbTransaction transaction, Nullable`1 commandTimeout)_

**Possible solution:**
![DapperExtensionsFix](https://user-images.githubusercontent.com/32682445/126969006-3133145e-1cac-46f5-b2e2-d21f74c99a33.PNG)
![DapperExtensionsFixAsync](https://user-images.githubusercontent.com/32682445/126969013-ce6f7f53-71f2-4618-bc68-95ebd0a96d93.PNG)

I appreciate your support.

**Comment by valfrid-ly** [comment]
In your suggestion you are returning SYNC from an async method. Did you run the unit tests??

**Comment by valfrid-ly** [comment]
With the suggested change we have a problem in Async Method. 
![image](https://user-images.githubusercontent.com/29312511/127035802-8fdb93d3-e10c-424a-a96a-aa98944eebda.png)

And looking carefully you're changing the result type

Here is the original one returning Task<T>:
`public async Task<T> GetAsync<T>(IDbConnection connection, dynamic id, IDbTransaction transaction = null, int? commandTimeout = null, bool buffered = false,
            IList<IProjection> colsToSelect = null, IList<IReferenceMap> includedProperties = null) where T : class
        {
            return await Task.FromResult(InternalGet<T>(connection, id, transaction, commandTimeout, colsToSelect, includedProperties));
        }`

Here is your suggestion, returning T:
`public async Task<T> GetAsync<T>(IDbConnection connection, dynamic id, IDbTransaction transaction = null, int? commandTimeout = null, bool buffered = false,
            IList<IProjection> colsToSelect = null, IList<IReferenceMap> includedProperties = null) where T : class
        {
            return (T)InternalGet<T>(connection, id, transaction, commandTimeout, colsToSelect, includedProperties);
        }`

It'll cause issues for those who are expecting a Task to get their results like this:
`
function MyItem Foo()
{
  var myResult := await conn.GetAsync<Entities.MyItem>(new { Id = pk });
 return myResult.Result;
}
`

For the sync method the fix is ok

**Comment by hfrances** [comment]
Hello, thanks for your quick response. I have fixed my mistake in async methods according to your comment.

![DapperExtensionsFixAsync-2](https://user-images.githubusercontent.com/32682445/127130305-d909bcad-6c69-4479-9e69-7e8901676bfe.PNG)

**Comment by valfrid-ly** [comment]
The change in DapperAsyncExtensions is unnecessary as "Instance.GetAsync" already returns Task<T>
