### ISSUE TITLE
Load Maps from a differenet assembly

### ISSUE THREAD

**Issue by tmsmith** [tmsmith/Dapper-Extensions#33]
Add ability to load class maps from a different assembly.

**Comment by rpaschoal** [comment]
I know this is very old topic, @tmsmith did not reply to that, but in case someone has the same problem (Since I did), and I think it is very common to have same problem for N-layered applications, you can see the workaround bellow:

DapperExtensions.DapperExtensions.Configure(typeof(AutoClassMapper<>), new List<Assembly>() { typeof(YOURCLASSMap).GetTypeInfo().Assembly }, new SqlServerDialect());

Just put that line on your application startup and that is it, it will read all the class maps from the YOURCLASSMap assembly.

Cheers!
